# Generated by Django 5.1.7 on 2025-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteapp',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='websiteapp',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
