# Generated by Django 5.1.7 on 2025-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_alter_websiteapp_options_websiteapp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteapp',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
