# Generated by Django 5.1.7 on 2025-04-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_websiteapp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='websiteapp',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='websiteapp',
            name='slug',
        ),
        migrations.AddField(
            model_name='websiteapp',
            name='article_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteapp',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.group'),
        ),
    ]
