# Generated by Django 5.1.7 on 2025-04-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_group_alter_websiteapp_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteapp',
            old_name='article_slug',
            new_name='slug',
        ),
    ]
