# Generated by Django 5.1.7 on 2025-04-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteApp',
            new_name='Command',
        ),
    ]
