# Generated by Django 5.1.7 on 2025-04-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_rename_websiteapp_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='article_slug',
            new_name='slug',
        ),
    ]
