# Generated by Django 5.1.7 on 2025-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_rename_article_slug_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
