# Generated by Django 5.1.7 on 2025-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_alter_command_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='command',
            name='tag',
            field=models.ManyToManyField(blank=True, to='website_app.tag'),
        ),
    ]
