# Generated by Django 5.1.7 on 2025-05-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_alter_command_managers_command_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('pk',), 'verbose_name': 'Команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelManagers(
            name='command',
            managers=[
            ],
        ),
    ]
