# Generated by Django 5.1.7 on 2025-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0014_user_alter_command_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='link',
        ),
        migrations.AddField(
            model_name='command',
            name='confluence_link',
            field=models.URLField(blank=True, null=True, verbose_name='Confluence'),
        ),
        migrations.AddField(
            model_name='command',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='command',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='media/website_app/gif', verbose_name='GIF-Изображение'),
        ),
        migrations.AddField(
            model_name='command',
            name='rutube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Rutube'),
        ),
        migrations.AddField(
            model_name='command',
            name='vkontakte_link',
            field=models.URLField(blank=True, null=True, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='command',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/website_app/image', verbose_name='Изображение'),
        ),
    ]
