# Generated by Django 5.1.7 on 2025-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0015_remove_command_link_command_confluence_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
    ]
