# Generated by Django 5.0.6 on 2025-07-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/aro_app/image', verbose_name='Изображение'),
        ),
    ]
