# Generated by Django 5.0.6 on 2025-08-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_app', '0002_alter_command_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('group', 'pk'), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
